<?php
/**
 * CustomerDataRelationships
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Layer API
 *
 * Headless Commerce for Global Brands.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@commercelayer.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CustomerDataRelationships Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class CustomerDataRelationships implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'customer_data_relationships';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'customer_group' => '\OpenAPI\Client\Model\CustomerDataRelationshipsCustomerGroup',
        'customer_addresses' => '\OpenAPI\Client\Model\CustomerDataRelationshipsCustomerAddresses',
        'customer_payment_sources' => '\OpenAPI\Client\Model\CustomerDataRelationshipsCustomerPaymentSources',
        'customer_subscriptions' => '\OpenAPI\Client\Model\CustomerDataRelationshipsCustomerSubscriptions',
        'orders' => '\OpenAPI\Client\Model\AdyenPaymentDataRelationshipsOrder',
        'returns' => '\OpenAPI\Client\Model\CustomerDataRelationshipsReturns',
        'attachments' => '\OpenAPI\Client\Model\AvalaraAccountDataRelationshipsAttachments'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'customer_group' => null,
        'customer_addresses' => null,
        'customer_payment_sources' => null,
        'customer_subscriptions' => null,
        'orders' => null,
        'returns' => null,
        'attachments' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customer_group' => 'customer_group',
        'customer_addresses' => 'customer_addresses',
        'customer_payment_sources' => 'customer_payment_sources',
        'customer_subscriptions' => 'customer_subscriptions',
        'orders' => 'orders',
        'returns' => 'returns',
        'attachments' => 'attachments'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customer_group' => 'setCustomerGroup',
        'customer_addresses' => 'setCustomerAddresses',
        'customer_payment_sources' => 'setCustomerPaymentSources',
        'customer_subscriptions' => 'setCustomerSubscriptions',
        'orders' => 'setOrders',
        'returns' => 'setReturns',
        'attachments' => 'setAttachments'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customer_group' => 'getCustomerGroup',
        'customer_addresses' => 'getCustomerAddresses',
        'customer_payment_sources' => 'getCustomerPaymentSources',
        'customer_subscriptions' => 'getCustomerSubscriptions',
        'orders' => 'getOrders',
        'returns' => 'getReturns',
        'attachments' => 'getAttachments'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['customer_group'] = $data['customer_group'] ?? null;
        $this->container['customer_addresses'] = $data['customer_addresses'] ?? null;
        $this->container['customer_payment_sources'] = $data['customer_payment_sources'] ?? null;
        $this->container['customer_subscriptions'] = $data['customer_subscriptions'] ?? null;
        $this->container['orders'] = $data['orders'] ?? null;
        $this->container['returns'] = $data['returns'] ?? null;
        $this->container['attachments'] = $data['attachments'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customer_group
     *
     * @return \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerGroup|null
     */
    public function getCustomerGroup()
    {
        return $this->container['customer_group'];
    }

    /**
     * Sets customer_group
     *
     * @param \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerGroup|null $customer_group customer_group
     *
     * @return self
     */
    public function setCustomerGroup($customer_group)
    {
        $this->container['customer_group'] = $customer_group;

        return $this;
    }

    /**
     * Gets customer_addresses
     *
     * @return \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerAddresses|null
     */
    public function getCustomerAddresses()
    {
        return $this->container['customer_addresses'];
    }

    /**
     * Sets customer_addresses
     *
     * @param \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerAddresses|null $customer_addresses customer_addresses
     *
     * @return self
     */
    public function setCustomerAddresses($customer_addresses)
    {
        $this->container['customer_addresses'] = $customer_addresses;

        return $this;
    }

    /**
     * Gets customer_payment_sources
     *
     * @return \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerPaymentSources|null
     */
    public function getCustomerPaymentSources()
    {
        return $this->container['customer_payment_sources'];
    }

    /**
     * Sets customer_payment_sources
     *
     * @param \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerPaymentSources|null $customer_payment_sources customer_payment_sources
     *
     * @return self
     */
    public function setCustomerPaymentSources($customer_payment_sources)
    {
        $this->container['customer_payment_sources'] = $customer_payment_sources;

        return $this;
    }

    /**
     * Gets customer_subscriptions
     *
     * @return \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerSubscriptions|null
     */
    public function getCustomerSubscriptions()
    {
        return $this->container['customer_subscriptions'];
    }

    /**
     * Sets customer_subscriptions
     *
     * @param \OpenAPI\Client\Model\CustomerDataRelationshipsCustomerSubscriptions|null $customer_subscriptions customer_subscriptions
     *
     * @return self
     */
    public function setCustomerSubscriptions($customer_subscriptions)
    {
        $this->container['customer_subscriptions'] = $customer_subscriptions;

        return $this;
    }

    /**
     * Gets orders
     *
     * @return \OpenAPI\Client\Model\AdyenPaymentDataRelationshipsOrder|null
     */
    public function getOrders()
    {
        return $this->container['orders'];
    }

    /**
     * Sets orders
     *
     * @param \OpenAPI\Client\Model\AdyenPaymentDataRelationshipsOrder|null $orders orders
     *
     * @return self
     */
    public function setOrders($orders)
    {
        $this->container['orders'] = $orders;

        return $this;
    }

    /**
     * Gets returns
     *
     * @return \OpenAPI\Client\Model\CustomerDataRelationshipsReturns|null
     */
    public function getReturns()
    {
        return $this->container['returns'];
    }

    /**
     * Sets returns
     *
     * @param \OpenAPI\Client\Model\CustomerDataRelationshipsReturns|null $returns returns
     *
     * @return self
     */
    public function setReturns($returns)
    {
        $this->container['returns'] = $returns;

        return $this;
    }

    /**
     * Gets attachments
     *
     * @return \OpenAPI\Client\Model\AvalaraAccountDataRelationshipsAttachments|null
     */
    public function getAttachments()
    {
        return $this->container['attachments'];
    }

    /**
     * Sets attachments
     *
     * @param \OpenAPI\Client\Model\AvalaraAccountDataRelationshipsAttachments|null $attachments attachments
     *
     * @return self
     */
    public function setAttachments($attachments)
    {
        $this->container['attachments'] = $attachments;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


