<?php
/**
 * CustomerPasswordResetsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Layer API
 *
 * Headless Commerce for Global Brands.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@commercelayer.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerPasswordResetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerPasswordResetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for dELETECustomerPasswordResetsCustomerPasswordResetId
     *
     * Delete a customer password reset.
     *
     */
    public function testDELETECustomerPasswordResetsCustomerPasswordResetId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for gETCustomerPasswordResets
     *
     * List all customer password resets.
     *
     */
    public function testGETCustomerPasswordResets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for gETCustomerPasswordResetsCustomerPasswordResetId
     *
     * Retrieve a customer password reset.
     *
     */
    public function testGETCustomerPasswordResetsCustomerPasswordResetId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pATCHCustomerPasswordResetsCustomerPasswordResetId
     *
     * Update a customer password reset.
     *
     */
    public function testPATCHCustomerPasswordResetsCustomerPasswordResetId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pOSTCustomerPasswordResets
     *
     * Create a customer password reset.
     *
     */
    public function testPOSTCustomerPasswordResets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
