<?php
/**
 * ManualTaxCalculatorsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Commerce Layer API
 *
 * Headless Commerce for Global Brands.
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: support@commercelayer.io
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ManualTaxCalculatorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ManualTaxCalculatorsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for dELETEManualTaxCalculatorsManualTaxCalculatorId
     *
     * Delete a manual tax calculator.
     *
     */
    public function testDELETEManualTaxCalculatorsManualTaxCalculatorId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for gETManualTaxCalculators
     *
     * List all manual tax calculators.
     *
     */
    public function testGETManualTaxCalculators()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for gETManualTaxCalculatorsManualTaxCalculatorId
     *
     * Retrieve a manual tax calculator.
     *
     */
    public function testGETManualTaxCalculatorsManualTaxCalculatorId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pATCHManualTaxCalculatorsManualTaxCalculatorId
     *
     * Update a manual tax calculator.
     *
     */
    public function testPATCHManualTaxCalculatorsManualTaxCalculatorId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for pOSTManualTaxCalculators
     *
     * Create a manual tax calculator.
     *
     */
    public function testPOSTManualTaxCalculators()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
